grafana:
  enabled: false

alertmanager:
  enabled: false

defaultRules:
  rules:
    alertmanager: false
    etcd: false
    kubeScheduler: false
    kubeControllerManager: false

prometheus:
  prometheusSpec:
    retention: 1d
    retentionSize: 512MB
    scrapeInterval: 60s
    evaluationInterval: 60s
    walCompression: true
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 768Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi

prometheusOperator:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

kubeStateMetrics:
  enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

nodeExporter:
  enabled: false
