grafana:
  enabled: false

alertmanager:
  enabled: false

defaultRules:
  rules:
    alertmanager: false
    etcd: false
    kubeScheduler: false
    kubeControllerManager: false

prometheus:
  prometheusSpec:
    retention: 1d
    scrapeInterval: 60s
    evaluationInterval: 60s
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi

prometheusOperator:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

kubeStateMetrics:
  enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

nodeExporter:
  enabled: false
