apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml

configMapGenerator:
  - name: grafana-dashboard-k8s-views-global
    files:
      - k8s-views-global.json=../dashboards/k8s-views-global.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Kubernetes

  - name: grafana-dashboard-k8s-views-namespaces
    files:
      - k8s-views-namespaces.json=../dashboards/k8s-views-namespaces.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Kubernetes

  - name: grafana-dashboard-k8s-views-pods
    files:
      - k8s-views-pods.json=../dashboards/k8s-views-pods.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Kubernetes

  - name: grafana-dashboard-k8s-views-nodes
    files:
      - k8s-views-nodes.json=../dashboards/k8s-views-nodes.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Kubernetes

  - name: grafana-dashboard-prometheus-overview
    files:
      - prometheus-overview.json=../dashboards/prometheus-overview.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Platform

  - name: grafana-dashboard-argocd
    files:
      - argocd.json=../dashboards/argocd.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Platform
